### ISSUE TITLE
editor.createFeatureContainer(features) doesn't work as advertised

### ISSUE THREAD

**Issue by mojodna** [heremaps/xyz-maps#91]
`createFeatureContainer` fails when features are passed to the builder:

```javascript
const feature = editor.getFeature("<id>", layer);
editor.createFeatureContainer([feature]);
xyz-maps-editor.min.js:19 Uncaught TypeError: e.getProvider is not a function
    at e.add (xyz-maps-editor.min.js:19:114888)
    at e.push (xyz-maps-editor.min.js:19:92660)
    at e.createFeatureContainer (xyz-maps-editor.min.js:21:10611)
    at index.js:178:30
    at t.trigger (xyz-maps-common.min.js:5:5183)
    at x (xyz-maps-display.min.js:5:186164)
    at Tn.onPointerUp (xyz-maps-display.min.js:5:187068)
```

This works fine:

```javascript
const feature = editor.getFeature("<id>", layer);
const container = editor.createFeatureContainer();
container.push(feature);
```

**Comment by TerminalTim** [comment]
until now, the .createFeatureContainer function only supported passing features as a spread argument.
typescript is already showing an error for: "editor.createFeatureContainer([feature]);"

There's nothing against supporting arrays of features as well. i'll quickly add.

**Comment by mojodna** [comment]
Ohhhh, sorry. I didn't try spreading or realize that because I wasn't looking closely enough at the docs. Thanks!
